### ISSUE TITLE
Where to install?

### ISSUE THREAD

**Issue by Yzord** [whphhg/vanillacoind-web-ui#2]
Could you provide me the location where i have to install this? I installed it in my homedir, but i receive an empty page when i try to call it

http://s3.postimg.org/mxh7sb46r/Screen_Shot_2015_11_12_at_15_43_29.png

**Comment by whphhg** [comment]
Hey,

you can install it anywhere you prefer. Like I wrote in the previous issue, it should run without a running wallet but it won't display any wallet specific information. Currency conversion and block estimation should work without a running wallet, but that's about it.

For everything else you need a running wallet. You can install it using xCore's build-script (https://raw.githubusercontent.com/xCoreDev/vanillacoin-scripts/master/build-linux.sh).

There's a small caveat at the moment. You'll have to add this line after **git clone ...** in Github part:
```
cd vanillacoin-src && git checkout d31dcc03cd && cd ..
```

This "problem" happens when a new version is not ready to be deployed but is already pushed to github. An error is added to the source so it fails during compiling (#error "Do not deploy 60041(0.4.0) yet.").

The git checkout part will fetch the 0.3.9 branch instead of the already updated master (https://github.com/john-connor/vanillacoin/tree/d31dcc03cd33f389fb15a99320de97ca73447c7b).
